apiVersion: v1
kind: Service
metadata:
 name: nodejs-distroless-svc
 namespace: default
 labels:
   app: nodejs-distroless
   tier: frontend
   version: v1
spec:
 type: NodePort
 ports:
 - port: 3000
 selector:
    app: nodejs-distroless
    tier: frontend
    version: v1